"""final changes

Revision ID: 0108579ac6e4
Revises: f023ea9e962a
Create Date: 2023-03-10 13:26:48.328879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0108579ac6e4'
down_revision = 'f023ea9e962a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
