"""troubleshoot

Revision ID: 061fdf6c93d8
Revises: 6737930a8cf2
Create Date: 2023-03-09 09:38:30.065396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061fdf6c93d8'
down_revision = '6737930a8cf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
