"""Faker

Revision ID: 08a11394c8e3
Revises: 2739a083bb71
Create Date: 2023-03-08 21:57:38.463687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a11394c8e3'
down_revision = '2739a083bb71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
