"""troubleshoot

Revision ID: 13142d838a56
Revises: 324152a69807
Create Date: 2023-03-09 10:13:55.157366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13142d838a56'
down_revision = '324152a69807'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
