"""final changes

Revision ID: 23b07d7293b4
Revises: ee547181f518
Create Date: 2023-03-10 09:15:43.147174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b07d7293b4'
down_revision = 'ee547181f518'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
