"""added Tutors

Revision ID: 2739a083bb71
Revises: ef1a58875f49
Create Date: 2023-03-07 20:13:04.462896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2739a083bb71'
down_revision = 'ef1a58875f49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
