"""Faker

Revision ID: 338d9f0b83b0
Revises: 4b5ecb41ae5d
Create Date: 2023-03-08 22:17:06.008411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338d9f0b83b0'
down_revision = '4b5ecb41ae5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
