"""added student class

Revision ID: 3874183a356a
Revises: 0a43c4aef47b
Create Date: 2023-03-07 14:53:34.704158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3874183a356a'
down_revision = '0a43c4aef47b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
