"""Faker

Revision ID: 4b5ecb41ae5d
Revises: 08a11394c8e3
Create Date: 2023-03-08 22:04:17.972906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b5ecb41ae5d'
down_revision = '08a11394c8e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
