"""manual data

Revision ID: 6737930a8cf2
Revises: ad6c1913c711
Create Date: 2023-03-08 22:39:56.817952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6737930a8cf2'
down_revision = 'ad6c1913c711'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
