"""manual data

Revision ID: ad6c1913c711
Revises: 338d9f0b83b0
Create Date: 2023-03-08 22:30:04.733897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6c1913c711'
down_revision = '338d9f0b83b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
