"""final changes

Revision ID: b248dad0e210
Revises: 0108579ac6e4
Create Date: 2023-03-10 13:28:19.525913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b248dad0e210'
down_revision = '0108579ac6e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
