"""troubleshoot

Revision ID: bc2030c0f3a8
Revises: 13142d838a56
Create Date: 2023-03-09 10:19:54.162002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc2030c0f3a8'
down_revision = '13142d838a56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
