"""added Tutors

Revision ID: c319314a01bd
Revises: e124130e5f98
Create Date: 2023-03-07 19:51:23.443262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c319314a01bd'
down_revision = 'e124130e5f98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
