"""added Tutors

Revision ID: e124130e5f98
Revises: b97b3ba1e127
Create Date: 2023-03-07 19:50:06.679674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e124130e5f98'
down_revision = 'b97b3ba1e127'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
