"""troubleshoot

Revision ID: ec2123cf08ff
Revises: b43c31ebb38e
Create Date: 2023-03-09 10:07:32.654866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2123cf08ff'
down_revision = 'b43c31ebb38e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'phone')
    # ### end Alembic commands ###
