"""troubleshoot

Revision ID: ee547181f518
Revises: bc2030c0f3a8
Create Date: 2023-03-09 10:21:06.569604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee547181f518'
down_revision = 'bc2030c0f3a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
