"""added Tutors

Revision ID: ef1a58875f49
Revises: c319314a01bd
Create Date: 2023-03-07 19:55:20.064847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef1a58875f49'
down_revision = 'c319314a01bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
