"""final changes

Revision ID: f023ea9e962a
Revises: 23b07d7293b4
Create Date: 2023-03-10 13:24:49.867249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f023ea9e962a'
down_revision = '23b07d7293b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
